### PR TITLE
Adding Linux homework

### PR DESCRIPTION
**Pull request by karolchluba**

### CODE REVIEW

**Comment by ziobron** [comment]
✅ CI Passed - Task: linux
New user detected (@karolchluba).  Trying to automatically map accounts.

**Comment by ziobron** [comment]
✅ CI Passed - Task: linux
🏅 Granted 10 XP for @karolchluba

**Comment by karolchluba** [comment]
A bit strange that it doesn't go through "/bin", but '/bin' does :) It's worth mentioning in the Linux -> 0x0D homework section, as there is a pasted example with '/bin'. I thought it was an example that just needs to be rewritten.  I saw that a few people on discord also had the same problem :)

**Comment by ziobron** [comment]
> A bit strange that it doesn't go through "/bin", but '/bin' does :) It's worth mentioning in the Linux -> 0x0D homework section, as there is a pasted example with '/bin'. I thought it was an example that just needs to be rewritten. I saw that a few people on discord also had the same problem :)

Can you raise an Issue here with links where the problem occurs and where it is ok?

**Pull request closed without merging**
